version: '3'
services:
    mongo-cnf-1:
        container_name: "mongo-cnf-1"
        image: mongo:4.2
        ports:
            - "30101:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017
        links:
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
        restart: always

    mongo-cnf-2:
        container_name: "mongo-cnf-2"
        image: mongo:4.2
        ports:
            - "30102:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017
        restart: always

    mongo-cnf-3:
        container_name: "mongo-cnf-3"
        image: mongo:4.2
        ports:
            - "30103:27017"
        command: mongod --replSet cnf-serv --configsvr --port 27017
        restart: always 

    mongo-cnf-setup:
        container_name: "mongo-cnf-setup"
        image: mongo:4.2
        depends_on:
            - "mongo-cnf-1"
            - "mongo-cnf-2"
            - "mongo-cnf-3"
        links:
            - mongo-cnf-1:mongo-cnf-1
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGO1=mongo-cnf-1
            - MONGO2=mongo-cnf-2
            - MONGO3=mongo-cnf-3
            - RS=cnf-serv
            - PORT=27017
        entrypoint: [ "/scripts/setup-cnf.sh" ]

    mongo-1-2:
        container_name: "mongo-1-2"
        image: mongo:4.2
        ports:
            - "30012:27017"
        command: mongod --replSet rs1 --shardsvr --port 27017
        restart: always

    mongo-1-3:
        container_name: "mongo-1-3"
        image: mongo:4.2
        ports:
            - "30013:27017"
        command: mongod --replSet rs1 --shardsvr --port 27017
        restart: always

    mongo-1-1:
        container_name: "mongo-1-1"
        image: mongo:4.2
        ports:
            - "30011:27017"
        command: mongod --replSet rs1 --shardsvr --port 27017
        links:
            - mongo-1-2:mongo-1-2
            - mongo-1-3:mongo-1-3
        restart: always

    mongo-rs1-setup:
        container_name: "mongo-rs1-setup"
        image: mongo:4.2
        depends_on:
            - "mongo-1-1"
            - "mongo-1-2"
            - "mongo-1-3"
        links:
            - mongo-1-1:mongo-1-1
            - mongo-1-2:mongo-1-2
            - mongo-1-3:mongo-1-3
        volumes:
            - ./scripts:/scripts
        environment:
            - MONGO1=mongo-1-1
            - MONGO2=mongo-1-2
            - MONGO3=mongo-1-3
            - RS=rs1
        entrypoint: [ "/scripts/setup.sh" ]

    mongo-router:
        container_name: "mongo-router"
        image: mongo:4.2
        ports:
            - "30001:27017"
        depends_on:
            - "mongo-rs1-setup"
            - "mongo-cnf-setup"
        external_links:
            - mongo-cnf-1:mongo-cnf-1
            - mongo-cnf-2:mongo-cnf-2
            - mongo-cnf-3:mongo-cnf-3
            - mongo-1-1:mongo-1-1
            - mongo-1-2:mongo-1-2
            - mongo-1-3:mongo-1-3
        command: mongos --configdb cnf-serv/mongo-cnf-1:27017,mongo-cnf-2:27017,mongo-cnf-3:27017 --port 27017 --bind_ip 0.0.0.0
        restart: always

    mongo-shard-setup:
        container_name: "mongo-shard-setup"
        image: mongo:4.2
        depends_on:
            - "mongo-router"
        links:
            - mongo-router:mongo-router
        volumes:
            - ./scripts:/scripts
        environment: 
            - MONGOS=mongo-router
            - MONGO11=mongo-1-1
            - MONGO12=mongo-1-2
            - MONGO13=mongo-1-3
            - RS1=rs1
            - PORT=27017
            - PORT1=27017
            - PORT2=27017
            - PORT3=27017
        entrypoint: [ "/scripts/init-shard.sh" ]
        restart: on-failure:20
